server:
  port: 6061

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.159.216.169:3306/intelligence_bi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: monv205850
    type: com.alibaba.druid.pool.DruidDataSource

    #druid 数据源专有配置
    druid:
      # 初始化时建立的连接个数
      initial-size: 5
      # 空闲时的最小连接个数
      min-idle: 5
      # 最大连接个数
      max-active: 20
      # 获取连接时的最大等待时间 单位为毫秒
      max-wait: 60000
      # 申请连接时的检测，如果空闲时间大于timeBetweenEvictionRunsMillis，则会执行validationQuery
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间是否大于该差值，如果大于则关闭连接
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql
      validation-query: select 'x'
      # 申请连接时会执行validationQuery来检测连接是否有效，开启会降低性能，默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效，开启会降低性能，默认为true
      test-on-return: false
      # 是否缓存preparedStatements
      pool-prepared-statements: true
      # 当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 2020
      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority 需要导入log4j依赖
      filters: stat,wall,log4j
      # 通过connectProperties来开启mergeSql功能和慢sql记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      stat-view-servlet:
        login-username: admin
        login-password: admin

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER